[battery-lion-utility-advanced]
name = "E_BATT-LION-2HR"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "advanced"
start_year = 2021
end_year = 2050
capital_costs_kw = [299, 336, 242, 228, 216, 207, 198, 189, 181, 171, 167, 164, 162, 159, 155, 153, 150, 146, 143, 141, 138, 134, 131, 129, 126, 122, 119, 117, 114, 110]
capital_costs_kwh = [322, 362, 260, 246, 233, 223, 214, 204, 193, 184, 181, 177, 174, 171, 168, 164, 161, 158, 155, 151, 148, 145, 142, 139, 135, 132, 129, 126, 122, 120]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 15
roundtrip_efficiency = 0.85
cost_unit = "USD"
cost_year = 2021
capacity_unit = "kW"
activity_unit = "MWh"
data_source = "NREL ATB (2023)"
outage_forced = 0
outage_planned = 0



[battery-lion-utility-moderate]
name = "E_BATT-LION-2HR"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "moderate"
start_year = 2021
end_year = 2050
capital_costs_kw = [299, 336, 329, 321, 288, 289, 290, 291, 293, 294, 292, 290, 288, 286, 284, 282, 280, 277, 275, 273, 271, 269, 267, 264, 262, 260, 257, 255, 253, 250]
capital_costs_kwh = [322, 362, 347, 329, 287, 275, 263, 251, 239, 227, 223, 219, 215, 211, 207, 203, 199, 194, 190, 186, 182, 178, 174, 170, 166, 162, 158, 154, 150, 146]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 15
roundtrip_efficiency = 0.85
cost_unit = "USD"
cost_year = 2021
capacity_unit = "kW"
activity_unit = "MWh"
data_source = "NREL ATB (2023)"
outage_forced = 0
outage_planned = 0

[battery-lion-utility-conservative]

name = "E_BATT-LION-2HR"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "conservative"
start_year = 2021
end_year = 2050
capital_costs_kw = [299, 336, 348, 351, 347, 340, 334, 327, 320, 313, 311, 309, 307, 304, 302, 300, 298, 296, 294, 292, 289, 287, 285, 283, 281, 279, 277, 274, 272, 270]
capital_costs_kwh = [322, 362, 376, 378, 373, 357, 341, 326, 310, 295, 293, 291, 289, 287, 285, 283, 281, 279, 277, 275, 273, 271, 269, 267, 265, 263, 261, 259, 257, 255]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 15
roundtrip_efficiency = 0.85
cost_unit = "USD"
cost_year = 2021
capacity_unit = "kW"
activity_unit = "MWh"
data_source = "NREL ATB (2023)"
outage_forced = 0
outage_planned = 0
