[metadata]
file_version = "1.0"
last_updated = "2023-01-01"
comment = "This configuration file contains the setup for various energy technologies under different scenarios."

[defaults]
data_source = "NREL ATB (2023)"
capacity_unit = "kW"
activity_unit = "MWh"
sector = "storage"
cost_year = 2021
cost_unit = "none" # none, k, M, B.
currency = "USD"
start_year = 2021
end_year = 2050

[battery-lion-utility-advanced]
name = "E_BATT-LION"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "advanced"
capital_costs_capacity = [299, 336, 242, 228, 216, 207, 198, 189, 181, 171, 167, 164, 162, 159, 155, 153, 150, 146, 143, 141, 138, 134, 131, 129, 126, 122, 119, 117, 114, 110]
capital_costs_energy = [322, 362, 260, 246, 233, 223, 214, 204, 193, 184, 181, 177, 174, 171, 168, 164, 161, 158, 155, 151, 148, 145, 142, 139, 135, 132, 129, 126, 122, 120]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 20
roundtrip_efficiency = 0.85
outage_forced = 0
outage_planned = 0
capacity_credit = 0.3


[battery-lion-utility-moderate]
name = "E_BATT-LION"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "moderate"
capital_costs_capacity = [299, 336, 329, 321, 288, 289, 290, 291, 293, 294, 292, 290, 288, 286, 284, 282, 280, 277, 275, 273, 271, 269, 267, 264, 262, 260, 257, 255, 253, 250]
capital_costs_energy = [322, 362, 347, 329, 287, 275, 263, 251, 239, 227, 223, 219, 215, 211, 207, 203, 199, 194, 190, 186, 182, 178, 174, 170, 166, 162, 158, 154, 150, 146]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 20
roundtrip_efficiency = 0.85
outage_forced = 0
outage_planned = 0
capacity_credit = 0.3

[battery-lion-utility-conservative]

name = "E_BATT-LION"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "conservative"
capital_costs_capacity = [299, 336, 348, 351, 347, 340, 334, 327, 320, 313, 311, 309, 307, 304, 302, 300, 298, 296, 294, 292, 289, 287, 285, 283, 281, 279, 277, 274, 272, 270]
capital_costs_energy = [322, 362, 376, 378, 373, 357, 341, 326, 310, 295, 293, 291, 289, 287, 285, 283, 281, 279, 277, 275, 273, 271, 269, 267, 265, 263, 261, 259, 257, 255]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 20
roundtrip_efficiency = 0.85
outage_forced = 0
outage_planned = 0
capacity_credit = 0.3

[battery-LDES-dummy]
# uses conservate power costs; and 10% of advanced energy costs
name = "E_BATT-LDES"
capacity = -1  # Typical unit size, in MW. Use "-1" if not applicable.
class = -1 # -1 for not applicable.
scenario = "advanced"
capital_costs_capacity = [299, 336, 348, 351, 347, 340, 334, 327, 320, 313, 311, 309, 307, 304, 302, 300, 298, 296, 294, 292, 289, 287, 285, 283, 281, 279, 277, 274, 272, 270]
capital_costs_energy = [32.2, 36.2, 26.0, 24.6, 23.3, 22.3, 21.4, 20.4, 19.3, 18.4, 18.1, 17.7, 17.4, 17.1, 16.8, 16.4, 16.1, 15.8, 15.5, 15.1, 14.8, 14.5, 14.2, 13.9, 13.5, 13.2, 12.9, 12.6, 12.2, 12.0]
fixed_costs_percent = 0.025 # Percent of total capital costs
variable_costs = 0
wacc = 0.04 # Assumption
capital_recovery_period = 15
lifetime = 20
roundtrip_efficiency = 0.85
outage_forced = 0
outage_planned = 0
capacity_credit = 0.3